"use strict";

// Module: out-build/vs/editor/common/editorContextKeys.js
// Offset: 824389 (bundle byte offset)
// Size: 4994 bytes
Ht();
si();
(function (n) {
  n.editorSimpleInput = new Sn("editorSimpleInput", false, true);
  n.editorTextFocus = new Sn("editorTextFocus", false, _(781, null));
  n.editorHasPromptBar = new Sn("editorHasPromptBar", false, _(782, null));
  n.editorPromptBarFocused = new Sn("editorPromptBarFocused", false, _(783, null));
  n.focus = new Sn("editorFocus", false, _(784, null));
  n.textInputFocus = new Sn("textInputFocus", false, _(785, null));
  n.readOnly = new Sn("editorReadonly", false, _(786, null));
  n.inDiffEditor = new Sn("inDiffEditor", false, _(787, null));
  n.isEmbeddedDiffEditor = new Sn("isEmbeddedDiffEditor", false, _(788, null));
  n.multiDiffEditorAllCollapsed = new Sn("multiDiffEditorAllCollapsed", undefined, _(789, null));
  n.hasChanges = new Sn("diffEditorHasChanges", false, _(790, null));
  n.comparingMovedCode = new Sn("comparingMovedCode", false, _(791, null));
  n.accessibleDiffViewerVisible = new Sn("accessibleDiffViewerVisible", false, _(792, null));
  n.diffEditorRenderSideBySideInlineBreakpointReached = new Sn("diffEditorRenderSideBySideInlineBreakpointReached", false, _(793, null));
  n.diffEditorInlineMode = new Sn("diffEditorInlineMode", false, _(794, null));
  n.diffEditorOriginalWritable = new Sn("diffEditorOriginalWritable", false, _(795, null));
  n.diffEditorModifiedWritable = new Sn("diffEditorModifiedWritable", false, _(796, null));
  n.diffEditorOriginalUri = new Sn("diffEditorOriginalUri", "", _(797, null));
  n.diffEditorModifiedUri = new Sn("diffEditorModifiedUri", "", _(798, null));
  n.columnSelection = new Sn("editorColumnSelection", false, _(799, null));
  n.writable = n.readOnly.toNegated();
  n.hasNonEmptySelection = new Sn("editorHasSelection", false, _(800, null));
  n.hasOnlyEmptySelection = n.hasNonEmptySelection.toNegated();
  n.hasMultipleSelections = new Sn("editorHasMultipleSelections", false, _(801, null));
  n.hasSingleSelection = n.hasMultipleSelections.toNegated();
  n.tabMovesFocus = new Sn("editorTabMovesFocus", false, _(802, null));
  n.tabDoesNotMoveFocus = n.tabMovesFocus.toNegated();
  n.isInEmbeddedEditor = new Sn("isInEmbeddedEditor", false, true);
  n.canUndo = new Sn("canUndo", false, true);
  n.canRedo = new Sn("canRedo", false, true);
  n.hoverVisible = new Sn("editorHoverVisible", false, _(803, null));
  n.hoverFocused = new Sn("editorHoverFocused", false, _(804, null));
  n.stickyScrollFocused = new Sn("stickyScrollFocused", false, _(805, null));
  n.stickyScrollVisible = new Sn("stickyScrollVisible", false, _(806, null));
  n.standaloneColorPickerVisible = new Sn("standaloneColorPickerVisible", false, _(807, null));
  n.standaloneColorPickerFocused = new Sn("standaloneColorPickerFocused", false, _(808, null));
  n.inCompositeEditor = new Sn("inCompositeEditor", undefined, _(809, null));
  n.notInCompositeEditor = n.inCompositeEditor.toNegated();
  n.languageId = new Sn("editorLangId", "", _(810, null));
  n.hasCompletionItemProvider = new Sn("editorHasCompletionItemProvider", false, _(811, null));
  n.hasCodeActionsProvider = new Sn("editorHasCodeActionsProvider", false, _(812, null));
  n.hasCodeLensProvider = new Sn("editorHasCodeLensProvider", false, _(813, null));
  n.hasDefinitionProvider = new Sn("editorHasDefinitionProvider", false, _(814, null));
  n.hasDeclarationProvider = new Sn("editorHasDeclarationProvider", false, _(815, null));
  n.hasImplementationProvider = new Sn("editorHasImplementationProvider", false, _(816, null));
  n.hasTypeDefinitionProvider = new Sn("editorHasTypeDefinitionProvider", false, _(817, null));
  n.hasHoverProvider = new Sn("editorHasHoverProvider", false, _(818, null));
  n.hasDocumentHighlightProvider = new Sn("editorHasDocumentHighlightProvider", false, _(819, null));
  n.hasDocumentSymbolProvider = new Sn("editorHasDocumentSymbolProvider", false, _(820, null));
  n.hasReferenceProvider = new Sn("editorHasReferenceProvider", false, _(821, null));
  n.hasRenameProvider = new Sn("editorHasRenameProvider", false, _(822, null));
  n.hasSignatureHelpProvider = new Sn("editorHasSignatureHelpProvider", false, _(823, null));
  n.hasInlayHintsProvider = new Sn("editorHasInlayHintsProvider", false, _(824, null));
  n.hasDocumentFormattingProvider = new Sn("editorHasDocumentFormattingProvider", false, _(825, null));
  n.hasDocumentSelectionFormattingProvider = new Sn("editorHasDocumentSelectionFormattingProvider", false, _(826, null));
  n.hasMultipleDocumentFormattingProvider = new Sn("editorHasMultipleDocumentFormattingProvider", false, _(827, null));
  n.hasMultipleDocumentSelectionFormattingProvider = new Sn("editorHasMultipleDocumentSelectionFormattingProvider", false, _(828, null));
  n.hasDisplayedDiff = new Sn("hasDisplayedDiff", false, "Whether the editor has pending edits.");
  n.hasActivelyGeneratingDiff = new Sn("hasActivelyGeneratingDiff", false, "Whether the editor is currently generating an edit.");
  n.hasFastCopilotDiffSuggestion = new Sn("hasFastCopilotDiffSuggestion", false, "Whether the editor is currently showing a fast copilot diff suggestion.");
  n.hasGPT4InlineCompletion = new Sn("hasGPT4Diff", false, "Whether the editor is showing a gpt-4 supercompletion");
  n.hasGPT4ActivelyGenerating = new Sn("hadGPT4InlineCompletionRunning", false, "Whether the editor had a gpt-4 supercompletion running");
})(Ci ||= {});
