"use strict";

// Module: out-build/vs/platform/reactivestorage/browser/utilities.js
// Offset: 4155802 (bundle byte offset)
// Size: 4442 bytes
qp();
ml();
kr();
mvA();
gvA();
L9t = {
  lastUpdateHiddenTimeInUnixSeconds: uae(0),
  lastUpdateHiddenVersion: tPe(""),
  updatePromptLastPromptTime: uae(0),
  updatePromptPromptsShownForVersion: xvt({}),
  updatePromptPromptsShownToday: uae(0),
  updatePromptPromptsShownTodayDate: tPe(""),
  updatePromptSnoozedUntilTime: uae(0),
  updatePromptForceUpdate: l_(false),
  settingsDismissedOpenAIKeyWarning: l_(false),
  settingsDismissedClaudeKeyWarning: l_(false),
  settingsDismissedGoogleKeyWarning: l_(false),
  settingsDismissedBedrockKeyWarning: l_(false),
  bestOfNCountPreference: uae(1),
  bestOfNEnsemblePreferences: tPe("{}"),
  lastSingleModelPreference: tPe("{}"),
  lastTimeClosedPaymentFailed: uae(0),
  lastPaymentFailed: l_(false),
  pendingCancellationDate: tPe(""),
  hasClickedSlackConnect: l_(false),
  markdownTestString: tPe(""),
  claudeMdEnabled: l_(false),
  thirdPartyExtensibilityEnabled: l_(true),
  importPluginsFromClaudeOnBoot: l_(true),
  composerAutocompleteHeuristicsEnabled: l_(false),
  composerAutocompleteHeuristicsAutoApplied: l_(false),
  githubPullRequestBetaEnabled: l_(false),
  jumpOnDiffAccept: l_(true),
  chatSubmitOnCmdEnter: l_(false),
  allowModelFallbacks: l_(true),
  numberOfTimesShownFallbackModelWarning: uae(0),
  isCursorDevToolsEnabled: l_(false),
  needsComposerInitialOpening: l_(true, 1, 0),
  shouldMockCursorPrediction: l_(false, 1, 0),
  isRcpInternalExtensionEnabled: l_(false, 1, 0),
  indexingData: xvt({
    preferredEmbeddingModel: AT.UNSPECIFIED
  }, 1, 0),
  uniqueCppWorkspaceId: tPe("", 1, 0),
  isComposerBarChatCollapsed: l_(false, 1, 0),
  shouldShowAgentWindowTitleHelperText: l_(true, 0, 0),
  composerBarPosition: xvt(null, 1, 0),
  devToolsPosition: xvt({
    x: 0,
    y: 0
  }, 1, 0),
  shouldExplicitlyShowFgComposerInBg: l_(false, 1, 0),
  enableDataHandleDebugging: l_(false, 1, 0),
  visualizeLoadedHandles: l_(false, 1, 0),
  approvedProjectMcpServers: P9t([], -1, 0),
  disabledMcpServers: P9t([], 1, 0),
  workspaceEligibleForSnippetLearning: l_(false, 1, 0),
  releaseTrackAppliedAt: uae(0, -1, 0),
  copyPasteMentions: P9t([], -1, 0),
  disposableTrackingEnabled: l_(false, -1, 0),
  autoRunBugbotOnCommit: l_(false, -1, 0),
  autoRunBugbotOnComposerFinish: l_(true, -1, 0),
  allowPromotionalAgentReviewRuns: l_(true, -1, 0),
  lastCloudHandoffUpsellAtUnixMs: uae(0, -1, 0),
  worktreeCleanupIntervalHours: uae(6, -1, 0),
  worktreeMaxCount: uae(20, -1, 0),
  voiceInputLanguage: tPe("en-US", -1, 0),
  hideAllBugbotFeatures: l_(false, -1, 0),
  bugbotIncludeSubmodules: l_(true, -1, 0),
  bugbotIncludeUntrackedFiles: l_(true, -1, 0),
  bugbotDeepReviewDefault: l_(false, -1, 0),
  attributeCommitsToAgent: l_(true, -1, 0),
  attributePRsToAgent: l_(true, -1, 0),
  disabledTeamRules: P9t([], -1, 0),
  agentLayoutDiffViewMode: ZUo(xY.Default, -1, 0),
  hasSeenAgentWindowWalkthrough: l_(false, -1, 0),
  unifiedAppLayout: ZUo(N0.Editor, -1, 0),
  extensionSigningVerificationEnabled: l_(false, -1, 0),
  extensionSigningEnabledAt: uae(0, -1, 0),
  grandfatheredExtensionHashes: xvt({}, -1, 0),
  defaultLayoutMode: tPe("sync", -1, 0),
  autoHideEditorWhenEmpty: l_(false, -1, 0),
  globalLayoutState: xvt(null, -1, 0),
  sandboxSupported: l_(false, 1, 0),
  sandboxNetworkDefault: {
    fromStorage: n => n === "ask" ? "user_config_with_defaults" : n === "enabled" ? "allow_all" : n === "user_config_only" || n === "user_config_with_defaults" || n === "allow_all" ? n : "user_config_with_defaults",
    toStorage: n => n,
    defaultValue: "user_config_with_defaults",
    storageScope: -1,
    storageTarget: 0
  },
  sandboxingSeen: l_(false, -1, 0),
  sandboxPromoVersionSeen: uae(0, -1, 0),
  sandboxDebugOutputDir: tPe("", -1, 0),
  terminalExecutionServiceV3HealthCheckResult: ZUo("untested", -1, 0),
  planExecUseChatModel: l_(true, -1, 0),
  planExecMode: ZUo("agent", -1, 0),
  worktreeSetupWarningShownCount: uae(0, 1, 0),
  hideWorktreeSetupWarning: l_(false, -1, 0),
  indexingGrepEnabled: l_(true, 1, 0),
  shouldShowNALIndicator: l_(false, -1, 0),
  autoOpenLocalhostUrls: l_(true, -1, 0),
  composerFileListExpanded: l_(true, 1, 0),
  browserUrlPopupDismissed: l_(false, -1, 0),
  pinnedComposers: P9t([], 1, 0),
  dismissedAutoOpenDialog: l_(false, -1, 0),
  markdownEditorModePreferences: xvt({}, -1, 0),
  noInlineDiffs: KHh(null, -1, 0),
  autoFormatOnAgentFinish: KHh(null, -1, 0),
  isPostOnboardingFirstLanding: l_(false, -1, 0),
  newChatAutoSwitchApplied: l_(false, -1, 0),
  conversionModelOverrideAppliedAuthIds: P9t([], -1, 0)
};
