"use strict";

// Module: out-build/vs/base/common/json.js
// Offset: 27623749 (bundle byte offset)
// Size: 6521 bytes
(function (n) {
  n[n.None = 0] = "None";
  n[n.UnexpectedEndOfComment = 1] = "UnexpectedEndOfComment";
  n[n.UnexpectedEndOfString = 2] = "UnexpectedEndOfString";
  n[n.UnexpectedEndOfNumber = 3] = "UnexpectedEndOfNumber";
  n[n.InvalidUnicode = 4] = "InvalidUnicode";
  n[n.InvalidEscapeCharacter = 5] = "InvalidEscapeCharacter";
  n[n.InvalidCharacter = 6] = "InvalidCharacter";
})(LJg ||= {});
(function (n) {
  n[n.OpenBraceToken = 1] = "OpenBraceToken";
  n[n.CloseBraceToken = 2] = "CloseBraceToken";
  n[n.OpenBracketToken = 3] = "OpenBracketToken";
  n[n.CloseBracketToken = 4] = "CloseBracketToken";
  n[n.CommaToken = 5] = "CommaToken";
  n[n.ColonToken = 6] = "ColonToken";
  n[n.NullKeyword = 7] = "NullKeyword";
  n[n.TrueKeyword = 8] = "TrueKeyword";
  n[n.FalseKeyword = 9] = "FalseKeyword";
  n[n.StringLiteral = 10] = "StringLiteral";
  n[n.NumericLiteral = 11] = "NumericLiteral";
  n[n.LineCommentTrivia = 12] = "LineCommentTrivia";
  n[n.BlockCommentTrivia = 13] = "BlockCommentTrivia";
  n[n.LineBreakTrivia = 14] = "LineBreakTrivia";
  n[n.Trivia = 15] = "Trivia";
  n[n.Unknown = 16] = "Unknown";
  n[n.EOF = 17] = "EOF";
})(NJg ||= {});
(function (n) {
  n[n.InvalidSymbol = 1] = "InvalidSymbol";
  n[n.InvalidNumberFormat = 2] = "InvalidNumberFormat";
  n[n.PropertyNameExpected = 3] = "PropertyNameExpected";
  n[n.ValueExpected = 4] = "ValueExpected";
  n[n.ColonExpected = 5] = "ColonExpected";
  n[n.CommaExpected = 6] = "CommaExpected";
  n[n.CloseBraceExpected = 7] = "CloseBraceExpected";
  n[n.CloseBracketExpected = 8] = "CloseBracketExpected";
  n[n.EndOfFileExpected = 9] = "EndOfFileExpected";
  n[n.InvalidCommentToken = 10] = "InvalidCommentToken";
  n[n.UnexpectedEndOfComment = 11] = "UnexpectedEndOfComment";
  n[n.UnexpectedEndOfString = 12] = "UnexpectedEndOfString";
  n[n.UnexpectedEndOfNumber = 13] = "UnexpectedEndOfNumber";
  n[n.InvalidUnicode = 14] = "InvalidUnicode";
  n[n.InvalidEscapeCharacter = 15] = "InvalidEscapeCharacter";
  n[n.InvalidCharacter = 16] = "InvalidCharacter";
})(MJg ||= {});
(function (n) {
  n.DEFAULT = {
    allowTrailingComma: true
  };
})(Hvi ||= {});
(function (n) {
  n[n.nullCharacter = 0] = "nullCharacter";
  n[n.maxAsciiCharacter = 127] = "maxAsciiCharacter";
  n[n.lineFeed = 10] = "lineFeed";
  n[n.carriageReturn = 13] = "carriageReturn";
  n[n.lineSeparator = 8232] = "lineSeparator";
  n[n.paragraphSeparator = 8233] = "paragraphSeparator";
  n[n.nextLine = 133] = "nextLine";
  n[n.space = 32] = "space";
  n[n.nonBreakingSpace = 160] = "nonBreakingSpace";
  n[n.enQuad = 8192] = "enQuad";
  n[n.emQuad = 8193] = "emQuad";
  n[n.enSpace = 8194] = "enSpace";
  n[n.emSpace = 8195] = "emSpace";
  n[n.threePerEmSpace = 8196] = "threePerEmSpace";
  n[n.fourPerEmSpace = 8197] = "fourPerEmSpace";
  n[n.sixPerEmSpace = 8198] = "sixPerEmSpace";
  n[n.figureSpace = 8199] = "figureSpace";
  n[n.punctuationSpace = 8200] = "punctuationSpace";
  n[n.thinSpace = 8201] = "thinSpace";
  n[n.hairSpace = 8202] = "hairSpace";
  n[n.zeroWidthSpace = 8203] = "zeroWidthSpace";
  n[n.narrowNoBreakSpace = 8239] = "narrowNoBreakSpace";
  n[n.ideographicSpace = 12288] = "ideographicSpace";
  n[n.mathematicalSpace = 8287] = "mathematicalSpace";
  n[n.ogham = 5760] = "ogham";
  n[n._ = 95] = "_";
  n[n.$ = 36] = "$";
  n[n._0 = 48] = "_0";
  n[n._1 = 49] = "_1";
  n[n._2 = 50] = "_2";
  n[n._3 = 51] = "_3";
  n[n._4 = 52] = "_4";
  n[n._5 = 53] = "_5";
  n[n._6 = 54] = "_6";
  n[n._7 = 55] = "_7";
  n[n._8 = 56] = "_8";
  n[n._9 = 57] = "_9";
  n[n.a = 97] = "a";
  n[n.b = 98] = "b";
  n[n.c = 99] = "c";
  n[n.d = 100] = "d";
  n[n.e = 101] = "e";
  n[n.f = 102] = "f";
  n[n.g = 103] = "g";
  n[n.h = 104] = "h";
  n[n.i = 105] = "i";
  n[n.j = 106] = "j";
  n[n.k = 107] = "k";
  n[n.l = 108] = "l";
  n[n.m = 109] = "m";
  n[n.n = 110] = "n";
  n[n.o = 111] = "o";
  n[n.p = 112] = "p";
  n[n.q = 113] = "q";
  n[n.r = 114] = "r";
  n[n.s = 115] = "s";
  n[n.t = 116] = "t";
  n[n.u = 117] = "u";
  n[n.v = 118] = "v";
  n[n.w = 119] = "w";
  n[n.x = 120] = "x";
  n[n.y = 121] = "y";
  n[n.z = 122] = "z";
  n[n.A = 65] = "A";
  n[n.B = 66] = "B";
  n[n.C = 67] = "C";
  n[n.D = 68] = "D";
  n[n.E = 69] = "E";
  n[n.F = 70] = "F";
  n[n.G = 71] = "G";
  n[n.H = 72] = "H";
  n[n.I = 73] = "I";
  n[n.J = 74] = "J";
  n[n.K = 75] = "K";
  n[n.L = 76] = "L";
  n[n.M = 77] = "M";
  n[n.N = 78] = "N";
  n[n.O = 79] = "O";
  n[n.P = 80] = "P";
  n[n.Q = 81] = "Q";
  n[n.R = 82] = "R";
  n[n.S = 83] = "S";
  n[n.T = 84] = "T";
  n[n.U = 85] = "U";
  n[n.V = 86] = "V";
  n[n.W = 87] = "W";
  n[n.X = 88] = "X";
  n[n.Y = 89] = "Y";
  n[n.Z = 90] = "Z";
  n[n.ampersand = 38] = "ampersand";
  n[n.asterisk = 42] = "asterisk";
  n[n.at = 64] = "at";
  n[n.backslash = 92] = "backslash";
  n[n.bar = 124] = "bar";
  n[n.caret = 94] = "caret";
  n[n.closeBrace = 125] = "closeBrace";
  n[n.closeBracket = 93] = "closeBracket";
  n[n.closeParen = 41] = "closeParen";
  n[n.colon = 58] = "colon";
  n[n.comma = 44] = "comma";
  n[n.dot = 46] = "dot";
  n[n.doubleQuote = 34] = "doubleQuote";
  n[n.equals = 61] = "equals";
  n[n.exclamation = 33] = "exclamation";
  n[n.greaterThan = 62] = "greaterThan";
  n[n.lessThan = 60] = "lessThan";
  n[n.minus = 45] = "minus";
  n[n.openBrace = 123] = "openBrace";
  n[n.openBracket = 91] = "openBracket";
  n[n.openParen = 40] = "openParen";
  n[n.percent = 37] = "percent";
  n[n.plus = 43] = "plus";
  n[n.question = 63] = "question";
  n[n.semicolon = 59] = "semicolon";
  n[n.singleQuote = 39] = "singleQuote";
  n[n.slash = 47] = "slash";
  n[n.tilde = 126] = "tilde";
  n[n.backspace = 8] = "backspace";
  n[n.formFeed = 12] = "formFeed";
  n[n.byteOrderMark = 65279] = "byteOrderMark";
  n[n.tab = 9] = "tab";
  n[n.verticalTab = 11] = "verticalTab";
})(FJg ||= {});
