"use strict";

// Module: out-build/vs/workbench/browser/parts/editor/editorCommands.js
// Offset: 31202471 (bundle byte offset)
// Size: 2285 bytes
G_();
zr();
Yr();
Js();
Yn();
lv();
Qh();
Ht();
ip();
dr();
hs();
Ei();
si();
wI();
Wt();
Hw();
Rf();
Fc();
Kl();
Pa();
sba();
h0i();
Afu();
Mm();
Nu();
Xq();
Zq();
nxe();
od();
AD();
ss();
_g();
L1t();
xDf();
ufn();
exe();
dfn = "workbench.action.closeUnmodifiedEditors";
Lit = "workbench.action.closeEditorsInGroup";
oka = "workbench.action.closeEditorsAndGroup";
aka = "workbench.action.closeEditorsToTheRight";
$ce = "workbench.action.closeActiveEditor";
Ifu = "workbench.action.closeActivePinnedEditor";
cka = "workbench.action.closeGroup";
f0i = "workbench.action.closeOtherEditors";
twe = "moveActiveEditor";
JMe = "copyActiveEditor";
GMe = "layoutEditorGroups";
lka = "workbench.action.keepEditor";
Dfu = "workbench.action.toggleKeepEditors";
uka = "workbench.action.toggleEditorGroupLock";
dka = "workbench.action.lockEditorGroup";
N1t = "workbench.action.unlockEditorGroup";
Bfu = "workbench.action.showEditorsInGroup";
b0i = "workbench.action.reopenWithEditor";
hka = "workbench.action.pinEditor";
Nit = "workbench.action.unpinEditor";
v0i = "workbench.action.splitEditor";
Mit = "workbench.action.splitEditorUp";
Jqe = "workbench.action.splitEditorDown";
Fit = "workbench.action.splitEditorLeft";
Gqe = "workbench.action.splitEditorRight";
A0i = "workbench.action.toggleMaximizeEditorGroup";
mka = "workbench.action.splitEditorInGroup";
DDf = "workbench.action.toggleSplitEditorInGroup";
pka = "workbench.action.joinEditorInGroup";
Rfu = "workbench.action.toggleSplitEditorInGroupLayout";
Pfu = "workbench.action.focusFirstSideEditor";
Lfu = "workbench.action.focusSecondSideEditor";
BDf = "workbench.action.focusOtherSideEditor";
RDf = "workbench.action.focusLeftGroupWithoutWrap";
PDf = "workbench.action.focusRightGroupWithoutWrap";
LDf = "workbench.action.focusAboveGroupWithoutWrap";
NDf = "workbench.action.focusBelowGroupWithoutWrap";
Nfu = "workbench.action.openEditorAtIndex";
y0i = "workbench.action.moveEditorToNewWindow";
gka = "workbench.action.copyEditorToNewWindow";
Mfu = "workbench.action.moveEditorGroupToNewWindow";
Ffu = "workbench.action.copyEditorGroupToNewWindow";
Ofu = "workbench.action.newEmptyEditorWindow";
vX = "_workbench.open";
Vme = "_workbench.diff";
MDf = "_workbench.openWith";
Ufu = [v0i, $ce, Nit, N1t, A0i];
$fu = function (n) {
  return !!$g(n) && !!Qo(n.to) && (!!Df(n.by) || !!Qo(n.by)) && (!!Df(n.value) || !!_1(n.value));
};
